import { StyleSheet } from "react-native"
export const styles = StyleSheet.create({
  container: {
    // marginBottom: 350,
    // flex: 1,
    // height: "100%",
    flexDirection: "column",
    zIndex: 5,
  },
  filter: {
    flex: 1,
    // backgroundColor: "green",
    flexDirection: "row",
    alignItems: "center",
    minHeight: 40,
    maxHeight: 60,
    // height: "100%",
    // width: "100%",
    zIndex: 10,
    justifyContent: "flex-end",
    // marginBottom: 100,
  },
  pickerWrapper: {
    // height: "100%",
    maxWidth: 150,
    marginLeft: 10,
    marginRight: 10,
  },
  picker: {
    // maxHeight: 30,
    // width: 150,
    // flex: 1,
    // margin: "0 5px",
    minHeight: 30,
    borderColor: "#9980FA",
    padding: 0,
    fontSize: 20,
    color: "#9980FA",
  },
  list: {
    // backgroundColor: "red",
    marginTop: 20,
    maxHeight: 500,
  },
})
